# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Padmanabhan Vijendran
title: Senior BigData Developer
email: padmanabhan5789@gmail.com
phone: +1 (647)-509-3692

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: amazingpaddy
stackoverflow_username: "3944252"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: amazingpaddy
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Download Resume
    icon: far fa-file-pdf
    url: https://amazingpaddy.github.io/resources/Padmanabhan_Vijendran_Resume.pdf
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  - IT professional with **12** years of experience in developing applications using **Java**, **Python** and **Big-Data technologies**.
  - **Google Cloud Certified Professional Data Engineer**.
  - Extensive expertise in working with **Hadoop**, **Spark 3.x**, **Spark Structured Streaming**, **Kafka**, **Hive** and **HBase**
  - Strong knowledge of **Python programming** and **Machine learning** concepts
  - Proficient in **UNIX commands** and **shell scripting**
  - Excellent analytical, communication and monitoring skills
  - Adaptable to different technologies and eager to learn new concepts quickly

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Technical Skills # Title for the section
    layout: text # Type of content section (list/text)
    content:  |
      - **Programming Languages:** Java, Python.
      - **Java EE Frameworks:** Spring MVC, Spring Data, Spring Security.
      - **Big-Data Frameworks:** Apache Spark, Kafka, Hive.
      - **Database skills:** SQL, HBase, MongoDB.
      - **Machine Learning:** Probability & Statistics, Linear Algebra, Pandas, numPy, EDA, KNN, Naive Byes.
      - **Cloud:** AWS, Azure, GCP.
      - **Automation Scripts:** Shell script, Batch Script, Powershell script, Selenium Python.
      - **DevOps:** Docker, Kubernetes, Jenkins, Tekton pipelines.
      - **Testing Frameworks:** JUnit 4, Cucumber.
      - **Build Tools:** Maven, Gradle.
      - **Version Control**: Git, GitHub, GitLab.
      - **Other Productivity Tools:** IntelliJ idea, Eclipse, Putty, Notepad++.

  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Royal Bank of Canada
        link: https://www.rbc.com/about-rbc.html
        # link_text: boringcompany.com
        sub_title: Lead Data Engineer
        caption: June 2023 - Present
        quote: >
          RBC is a global financial institution with a purpose-driven, principles-led approach to delivering leading performance, and creating value for our clients and communities.
        description: | # this will include new lines to allow paragraphs
          
          **Project Details**: As the lead developer, I spearheaded the design and development of RBC's End-of-Day Contract (EODc) Compliance Checker tool, leveraging Java 11. This tool serves various business sectors within RBC, including Retail and Capital Markets. The Compliance Checker automates the validation of daily contract reports, ensuring they meet both industry and internal standards. It flags any discrepancies, providing a robust solution for quality assurance and regulatory compliance across multiple lines of business.
          
          **Roles and Responsibilities**:
          - **Designed and Developed** the EODc Compliance Checker, a **Java-based** application that automates the validation of complex daily contract reports across multiple business lines.
          - **RESTful Web Services:** Leveraged **Apache Spring** to implement **REST services** that trigger the EODc report validation process, enhancing the tool's scalability and user interaction.
          - **Agile Collaboration:** Actively participated in **Agile** sprints, collaborated with Business Analysts to translate business needs into technical requirements, and ensured timely delivery of high-quality product.
          - **Quality Assurance:** Fixed bugs expediently while handling enhancement requests, ensuring optimal application performance and client satisfaction.
          - **High-Performance Computing:** Employed **multi-threading** techniques to process voluminous EODc data packages exceeding 200GB, featuring millions of lines in each file.
          - **Code Quality & Testing:** Implemented unit tests with an achievement of over 90% coverage, integrated **Sonar Lint** for code quality checks, and eliminated code smells.
          - **Regression Testing:** Developed functional test cases utilizing the **Cucumber Framework** to prevent regressions and ensure application stability across releases.
          - **DevOps Integration:** Optimized **Git** workflows and **CI/CD pipelines**, significantly accelerating the release process and increasing operational efficiency.
      - layout: left
        title: Cognizant Technology Solutions
        link: https://www.cognizant.com/ca/en
        # link_text: boringcompany.com
        sub_title: Senior Big-Data Developer
        caption: August 2021 - June 2023
        quote: >
          Cognizant is an American multinational information technology services and consulting company. It is headquartered in Teaneck, New Jersey, United States.
        description: | # this will include new lines to allow paragraphs
          **Client:** Ford, USA
          
          **Project Details**: Ford engineers use reports generated by an ETL framework to design future cars with low manufacturing costs. 
          We are migrating the ETL framework from Sqoop and Hive to Apache Spark Structured Streaming so that engineers can access near real-time reports.
          
          **Roles and Responsibilities**:
          - Migrated **ETL** framework from **Sqoop/Hive** to **Apache Spark Structured Streaming** for Ford Engineering.
          - Developed **Spark Structured Streaming** application using **pyspark** that reduced data processing time by 50% and increased report accuracy by 20%.
          - Implemented ETL pipelines using **Apache Spark**, **Kafka** and **MongoDB** that enabled engineers to utilize near real-time reports for designing future cars at low manufacturing cost.
          - Designed and developed **Java** application to efficiently fetch data from LDAP servers.
          - Refactored **Java** applications to improve readability and performance.
          - Explored new technologies using **POCs** and documented the approaches to implement new project requirements.
      - layout: left
        title: Credit Agricole CIB
        link: https://www.ca-cib.com/
        # link_text: boringcompany.com
        sub_title: Senior Big-Data Developer
        caption: March 2018 - July 2021
        quote: >
          Crédit Agricole Corporate and Investment Bank (Crédit Agricole CIB, formerly Crédit Agricole Indosuez then Calyon) is Crédit Agricole's corporate and investment banking entity.
        description: | # this will include new lines to allow paragraphs
          **Project Details**: CMT (Cash Management Transactions): Implemented an internal payment engine that handled incoming and outgoing transactions efficiently using Java 8, Spark structured streaming, Kafka, HBase and ELK stack. Delivered the project following Agile methodology.
          
          **Roles and Responsibilities**:
          - Implemented an internal payment engine using **Java-8** and **Spark structured streaming** that processed over 1 million transactions per day.
          - Developed an integration layer using **Spark structured streaming** and **Java-8** that enabled seamless communication between the payment engine and other applications.          
          - Designed and built a data pipeline using **Kafka**, **HBase** and **Spark** that ingested, stored and analyzed transaction data in real-time.
          - Created **Python** scripts to automate demo tool and performance report generation, reducing manual effort by 50%.
          - Created custom source and sink connectors for **IBM MQ** using **Spark structured streaming** that improved data reliability and throughput.
          - Developed **Jenkins pipelines** using **groovy** and **shell scripting** that facilitated continuous integration and delivery of code changes.
          - Automated functional testing using **Cucumber framework** that ensured high-quality code delivery.
          - Set up application logs using **ELK stack** and created dashboards for monitoring performance metrics.
      - layout: left
        title: Cognizant Technology Solutions
        link: https://www.cognizant.com
        # link_text: boringcompany.com
        sub_title: Big-Data Developer
        caption: February 2016 - November 2017
        quote: >
          Cognizant is an American multinational information technology services and consulting company. It is headquartered in Teaneck, New Jersey, United States.
        description: | # this will include new lines to allow paragraphs
          **Client:** Ford, USA
          
          **Project Details**: I worked on the project that generated reports to help Ford Engineer to design a future cars at low manufacturing cost. 
          We implemented ETL using BigData tools such as Apache Spark 2.3, Hive, Sqoop and Oozie. 
          
          **Roles and Responsibilities**:
          - Extracted data from various Oracle databases to **HDFS** and **Hive** using **Sqoop** scripts.
          - Transformed data to the required schema using **Hive** scripts.
          - Developed **Java** application to generate Excel reports from **Hive** table data using **Apache POI**.
          - Explored **ETL** with **Alteryx**, **Apache Spark** using POCs.
      - layout: left
        title: Tata Consultancy Services
        link: https://www.tcs.com
        # link_text: boringcompany.com
        sub_title: IT Analyst
        caption: January 2011 - January 2016
        quote: >
          Tata Consultancy Services (TCS) is an Indian multinational information technology (IT) services and consulting company with its headquarters in Mumbai.
        description: | # this will include new lines to allow paragraphs
          **Client:** Target, USA
          
          **Project Details**: I worked on the project that processed product images and details for Target website using ETL Java application and SQL scripts. 
          
          **Roles and Responsibilities**:
          - Developed **ETL** **Java** application to process product information using Map-Reduce
          - Wrote **SQL** queries to transform product related data
          - Automated manual tasks using **Python**
          - Investigated and analyzed **application support** incidents through to root cause and fix
          - Proactively monitored services and responded to alerts raised by customers and monitoring systems, ensuring the availability and performance of the **Teamsite** Content Management Systems
  - title: Certifications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - [Google Cloud Certified - Professional Data Engineer](https://www.credential.net/f1604fa8-370f-4e3e-acb0-20c6463ebc2c?key=f0e7a8bac1e57fb111633b61a4194c4b70fa9cf7e88e396472716a2a388d68bd)
      - [AWS Certified Cloud Practitioner](https://www.credly.com/badges/2cb6d504-93e8-4337-b3c9-b541ed5c4558/public_url)
      - [Microsoft Certified: Azure AI Fundamentals](https://www.credly.com/badges/5a2e8022-8d77-42e8-ab81-718a03b6d396)
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Anna University
        caption: 2006 - 2010
        sub_title: Bachelor Of Engineering - Electronics and Communications.
        quote: >
          Anna University is a public state university located in Tamil Nadu, India. The main campus is in Chennai. It was originally established on 4 September 1978 and is named after C. N. Annadurai, the former Chief Minister of Tamil Nadu.
        description: | # this will include new lines to allow paragraphs
          At the University, I acquired essential skills like teamwork and meeting tight deadlines that have been valuable throughout my career. Additionally, I relished my time there and gained knowledge about maintaining a healthy work-life balance.

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
